## function calling allows llms to call external tools, APIs, & DBs.
# the model decides when and how to use functions based on the conversation. 


from openai import OpenAI
import json
import os
from typing import Literal
client = OpenAI(api_key="##")

## Step 1 :  define available functions / tools 

def get_weather(location:str,unit:str="fahrenheit"):
    """ get current weather for a location"""
    
    # in real app a call weather api 
    
    return {
        "location":location,
        "temprature":"72",
        "unit":unit,
        "conditions":"sunny"
    }
    
def get_stock_price(stocks:list[str]) -> dict[str, Literal[]]:
    "get latest stock price for a perticular stock"
    
    # in real app call a stock checker api 
    
    prices = {"AAPL":"178.5", "GOOGL":"88.11","MSFT":"1122"}
    return {"stocks":stocks,"prices":prices}

# Step 2 : schema of function/toold to pass to the model
tools = [
    {
        "type":"function",
        "function":{
            "name":"get_weather",
            "description":"Get Weather",
            "parameters":{
                "type":"object",
                "properties":{
                    "location":{"type":"string"},
                    "unit": {"type": "string", "enum": ["celsius", "fahrenheit"]}
                },
                "required": ["location"]
            }
        }
    },
    {
        "type": "function",
        "name": "get_stock_price",
        "description": "Get stock price",
        "parameters": {
            "type": "object",
            "properties": {
                "symbol": {"type": "string"}
            },
            "required": ["symbol"]
        }
    }
]

# Create a running input list we will add to over time
input_lists = [
        {"role": "user", "content": "what is the weather in pune and HDFC stock price."},
]
# step 3 ask the model 
response = client.responses.create(
    model="gpt-4o",
    input=input_lists,
    tools=tools
)

# Step 4: Execute tool calls based on LLM Response

for function_call in response.output:
    if function_call.type == "function_call":
        
        name = function_call.name
        args = json.loads(function_call.arguments)
        
        if name =="get_weather":
            result = get_weather(**args)
        elif name == "get_stock_price":
            result = get_stock_price(**args)
            
        
        input_lists.append({
           "type":"function call output",
           "call_id": tool_call.id,
            "output": json.dumps(result)
        })
        
# Step 5 : send the result back to LLM 

final_response = client.responses.create(
    model="gpt-4",
    instructions="Respond only with a horoscope generated by a tool.",
    input=input_lists,
    tools=tools
)

print(final_response.output_text)